labels:
  small:
    description: Pull request is small
    color: "#76dbbe"
  medium:
    description: Pull request is medium
    color: "#2986cc"
  large:
    description: Pull request is large
    color: "#c90076"
workflows:
  - name: praise-contributors-on-milestones
    description: Praise contributors based on their contributions
    always-run: true
    if:
      - rule: $pullRequestCountBy($author()) == 1
        extra-actions:
          - $commentOnce($sprintf("Thank you @%s for this first contribution!", [$author()]))
      - rule: $pullRequestCountBy($author()) == 100
        extra-actions:
          - $commentOnce($sprintf("Way to go 🎉 This is your 100th pull request!", [$author()]))
  - name: check-conventional-commits
    description: Validate that pull requests follow the conventional commits
    always-run: true
    if:
      - rule: $isDraft() == false
    then:
      - $commitLint()
      - $titleLint()
  - name: best-practices
    description: Validate best practices for pull request management
    always-run: true
    if:
      - rule: $hasLinkedIssues() == false
        extra-actions:
          - $warn("Please link an issue to the pull request")
      - rule: $description() == ""
        extra-actions:
          - $warn("Please provide a description for the pull request")
      - rule: $hasLinearHistory() == false
        extra-actions:
          - $warn("Please rebase your pull request on the latest changes")
  - name: size-labelling
    description: Label pull request based on the number of lines changed
    always-run: true
    if:
      - rule: $size() < 100
        extra-actions:
          - $removeLabels(["medium", "large"])
          - $addLabel("small")
      - rule: $size() >= 100 && $size() < 300
        extra-actions:
          - $removeLabels(["small", "large"])
          - $addLabel("medium")
      - rule: $size() >= 300
        extra-actions:
          - $removeLabels(["small", "medium"])
          - $addLabel("large")
  - name: reviewer-assignment
    description: Assign a reviewer to pull requests
    always-run: true
    if:
      - rule: $isDraft() == false
        extra-actions:
          - $assignRandomReviewer()
  - name: check-approvals
    description: Check that pull requests have the required number of approvals
    always-run: true
    if:
      - rule: $isDraft() == false && $approvalsCount() < 1
        extra-actions:
          - $addLabel("waiting-for-review")
  - name: change-type-labelling
    description: Label pull requests based on the type of changes
    always-run: true
    if:
      - rule: $hasFileExtensions([".md", ".txt"])
        extra-actions:
          - $addLabel("docs")
      - rule: $hasFileExtensions([".tf"])
        extra-actions:
          - $addLabel("infra")
      - rule: $hasFileExtensions(["package.json", "package-lock.json"])
        extra-actions:
          - $addLabel("dependencies")
  - name: license-validation
    description: Validate that licenses are not modified
    always-run: true
    if:
      - rule: $hasFilePattern("**/LICENSE*")
        extra-actions:
          - $fail("License files cannot be modified")
