settings:
  commit_msg: "docs: update README.es.md with latest GitHub activity"
  readme_file: "./README.es.md"
  date:
    timezone: "Europe/Madrid"
messages:
  comments: "💬 Ha comentado a {ID} en {REPO}"
  issue_opened: "❗️ Ha abierto el tema {ID} en {REPO}"
  issue_closed: "✔️ Ha cerrado el tema {ID} en {REPO}"
  pr_opened: "💪 Ha abierto una PR {ID} en {REPO}"
  pr_closed: "❌ Ha cerrado una PR {ID} en {REPO}"
  pr_merged: "🎉 Ha fusionado una PR {ID} en {REPO}"
  create_repo: "📔 Ha creado un nuevo repositorio {REPO}"
  fork_repo: "🔱 Ha bifurcado {FORK} desde {REPO}"
  wiki_create: "📖 Ha creado una nueva wiki {WIKI} en {REPO}"
  added_member: "🤝 Se ha convertido en colaborador de {REPO}"
  changes_approved: "👍 Ha aprobado {ID} en {REPO}"
  changes_requested: "🔴 Ha pedido cambios a {ID} en {REPO}"
  new_release: "✌️ Ha publicado {ID} en {REPO}"
  new_star: "⭐ Ha destacado {REPO}"
  push: "⬆️ Ha empujado {AMOUNT} commit(s) en {REPO}"
