settings:
  commit_msg: "docs: update README.it.md with latest GitHub activity"
  readme_file: "./README.it.md"
  date:
    timezone: "Europe/Madrid"
messages:
  comments: "💬 Ha commentato {ID} in {REPO}"
  issue_opened: "❗Ha aperto il tema {ID} in {REPO}"
  issue_closed: "✔️Ha chiuso il tema {ID} in {REPO}"
  pr_opened: "💪 Ha aperto il PR {ID} in {REPO}"
  pr_closed: "❌ Ha chiuso il PR {ID} in {REPO}"
  pr_merged: "🎉 Ha unificato il PR {ID} in {REPO}"
  create_repo: "📔 Ha creato un nuovo repository {REPO}"
  fork_repo: "🔱 Ha biforcato {FORK} da {REPO}"
  wiki_create: "📖 Ha creato una nuova pagina wiki {WIKI} in {REPO}"
  added_member: "🤝 È un collaboratore di {REPO}"
  changes_approved: "👍 Ha approvato {ID} in {REPO}"
  changes_requested: "🔴 Ha richiesto dei cambi in {ID} in {REPO}"
  new_release: "✌️ Ha publicato {ID} in {REPO}"
  new_star: "⭐ Ha rimarcato {REPO}"
  push: "⬆️ Ha impulsato modifiche in {REPO}"
