name: 'Create and Auto-merge PR'
description: 'Creates a pull request and automatically merges it if successful'
author: 'fbuireu'
inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
  commit-message:
    description: 'Commit message for the PR'
    required: false
    default: 'docs: update repository assets'
  title:
    description: 'Title of the pull request'
    required: false
    default: '🤖 [AUTOMATED] Update Repository Assets'
  branch:
    description: 'Branch name for the pull request'
    required: false
    default: 'auto-update-${{ github.run_number }}'
  force-merge:
    description: 'Force merge without waiting for checks (use with caution)'
    required: false
    default: 'false'
outputs:
  pull-request-number:
    description: 'The number of the created pull request'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pull-request-operation:
    description: 'The operation performed (created, updated, or none)'
    value: ${{ steps.create-pr.outputs.pull-request-operation }}
runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ inputs.commit-message }}
        title: ${{ inputs.title }}
        body: |
          ## Automated Repository Update
          
          This PR contains updated assets generated automatically.
          
          **Generated on:** ${{ github.run_id }}
          **Workflow:** ${{ github.workflow }}
          **Triggered by:** ${{ github.event_name }}
          
          ---
          *This PR was created automatically and will be auto-merged if all checks pass.*
        branch: ${{ inputs.branch }}
        delete-branch: true
        base: main
    - name: Auto-merge PR
      if: steps.create-pr.outputs.pull-request-number && inputs.force-merge == 'false'
      shell: bash
      run: |
        echo "🚀 Enabling auto-merge..."
        
        gh pr ready ${{ steps.create-pr.outputs.pull-request-number }} || true
        gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash --subject "${{ inputs.commit-message }}"
        
        echo "✅ Auto-merge enabled. PR will merge when conditions are met."
      env:
        GH_TOKEN: ${{ inputs.token }}
    - name: Force merge with admin privileges
      if: steps.create-pr.outputs.pull-request-number && inputs.force-merge == 'true'
      shell: bash
      run: |
        echo "⚠️ Force merging PR with admin privileges..."
        
        gh pr ready ${{ steps.create-pr.outputs.pull-request-number }} || true
        gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --admin --squash --subject "${{ inputs.commit-message }}"
        
        echo "✅ PR force-merged with admin privileges!"
      env:
        GH_TOKEN: ${{ inputs.token }}
    - name: Report Status
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.create-pr.outputs.pull-request-operation }}" = "created" ]; then
          echo "✅ PR created: #${{ steps.create-pr.outputs.pull-request-number }}"
          
          if [ "${{ steps.create-pr.outputs.pull-request-number }}" != "" ]; then
            pr_state=$(gh pr view ${{ steps.create-pr.outputs.pull-request-number }} --json state --jq '.state' 2>/dev/null || echo "unknown")
            if [ "$pr_state" = "MERGED" ]; then
              echo "🎉 Status: Successfully merged!"
            else
              echo "⏳ Status: Auto-merge enabled"
              echo "🔗 View PR: ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull-request-number }}"
            fi
          fi
        elif [ "${{ steps.create-pr.outputs.pull-request-operation }}" = "updated" ]; then
          echo "✅ Existing PR updated: #${{ steps.create-pr.outputs.pull-request-number }}"
        else
          echo "ℹ️ No changes detected, no PR needed"
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
