name: Codeball
on:
  pull_request:
     types:
     - opened
     - reopened
     - synchronize
     - ready_for_review
  pull_request_review_comment:
    types: 
     - created
     - edited
jobs:
  codeball_job:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    name: Codeball
    steps:
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: true
          labelPullRequestsWhenApproved: true
          labelPullRequestsWhenReviewNeeded: false
          failJobsWhenReviewNeeded: false
