name: Commit Message

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Lint the pull request title
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: read
    steps:
      - name: Lint pull request title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
