name: Followers Notifier
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
permissions: {}
jobs:
  build:
    name: Followers Notifier
    runs-on: ubuntu-latest
    steps:
      - name: Get Followers Change
        id: followers_change
        uses: Sorosliu1029/follower-change@e86fa186d8680c55cbb048d3a9d8dcb8df5b4192 # v2
        with:
          myToken: ${{ secrets.FOLLOWERS_NOTIFIER_TOKEN }}
          notifyUnFollowEvent: true
      - name: Email Me
        uses: dawidd6/action-send-mail@42942bc2f8fba4e611b459a018967a6a7c78c68c # v17
        if: steps.followers_change.outputs.shouldNotify == 'true'
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          secure: true
          username: ${{ vars.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 👀🧑‍💻 GitHub Followers Change 🧑‍💻👀
          from: Follower Change Notifier <${{ vars.MAIL_USERNAME }}>
          to: ${{ vars.MAIL_USERNAME }}
          html_body: file://${{ steps.followers_change.outputs.htmlFilePath }}
