name: GitHub Star Tracker
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
permissions:
  contents: write
jobs:
  track-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Track star changes
        id: tracker
        uses: fbuireu/github-star-tracker@3c16394edea2f1117e87dd8a2ec716b18d84a1ac # v1.8.5
        with:
          github-token: ${{ secrets.PAT }}
          locale: en
          include-charts: true
          visibility: owned
          include-forks: false
          include-archived: false
          track-stargazers: true
          notification-threshold: auto
      - name: Send email report
        if: steps.tracker.outputs.stars-changed == 'true'
        uses: dawidd6/action-send-mail@42942bc2f8fba4e611b459a018967a6a7c78c68c # v17
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          secure: true
          username: ${{ vars.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '⭐ Star Tracker: ${{ steps.tracker.outputs.total-stars }} stars (GitHub Action) ⭐'
          from: GitHub Star Tracker <${{ vars.MAIL_USERNAME }}>
          to: ${{ vars.MAIL_USERNAME }}
          html_body: ${{ steps.tracker.outputs.report-html }}
