name: GitHub Star Tracker
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
permissions:
  contents: write
jobs:
  track-stars:
    name: Track GitHub Stars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true
      - name: Track star changes
        id: tracker
        uses: fbuireu/github-star-tracker@c4f67ea6b22304e16ff2a4ce8968719a388b587a # v1.21.1
        with:
          github-token: ${{ secrets.PAT }}
          locale: en
          include-charts: true
          visibility: owned
          include-forks: false
          include-archived: false
          track-stargazers: true
          notification-threshold: auto
      - name: Send email report
        if: steps.tracker.outputs.stars-changed == 'true'
        uses: dawidd6/action-send-mail@42942bc2f8fba4e611b459a018967a6a7c78c68c # v17
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          secure: true
          username: ${{ vars.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '⭐ Star Tracker: ${{ steps.tracker.outputs.total-stars }} stars (GitHub Action) ⭐'
          from: GitHub Star Tracker <${{ vars.MAIL_USERNAME }}>
          to: ${{ vars.MAIL_USERNAME }}
          html_body: ${{ steps.tracker.outputs.report-html }}
