name: GitHub Star Tracker
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
permissions:
  contents: write
jobs:
  track-stars:
    name: Track GitHub Stars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true
      - name: Track star changes
        id: tracker
        uses: fbuireu/github-star-tracker@08c374a4f5fc9750641c1408c8d2a3c03996943e # v1.22.0
        with:
          github-token: ${{ secrets.PAT }}
          locale: en
          include-charts: true
          visibility: owned
          include-forks: false
          include-archived: false
          track-stargazers: true
          notification-threshold: auto
      - name: Send email report
        if: steps.tracker.outputs.stars-changed == 'true'
        uses: dawidd6/action-send-mail@94de994a9f6fffee200243214e17002e2920bb59 # v18
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          secure: true
          username: ${{ vars.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '⭐ Star Tracker: ${{ steps.tracker.outputs.total-stars }} stars (GitHub Action) ⭐'
          from: GitHub Star Tracker <${{ vars.MAIL_USERNAME }}>
          to: ${{ vars.MAIL_USERNAME }}
          html_body: ${{ steps.tracker.outputs.report-html }}
