name: Hashnode Latest Articles
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update my README.md with latest blog posts from Hashnode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE-LATEST-ARTICLES"
          max_post_count: 5
          feed_list: "https://ferranbuireu.hashnode.dev/rss.xml"
