name: Hashnode Latest Articles
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Update ${{ matrix.readme }}
    runs-on: ubuntu-latest
    env:
      RSS_FILE: hashnode_feed.xml
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        readme: [README.md, README.ca.md, README.es.md, README.it.md]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Download RSS via proxy
        run: |
          curl -s "https://api.allorigins.win/get?url=${{ vars.HASHNODE_RSS }}" | \
          node -e "
            let data = '';
            process.stdin.on('data', chunk => data += chunk);
            process.stdin.on('end', () => {
              try {
                const json = JSON.parse(data);
                console.log(json.contents);
              } catch (e) {
                console.error('Error parsing JSON:', e);
                process.exit(1);
              }
            });
          " > ${{ env.RSS_FILE }}
      - name: Verify RSS file
        run: |
          if [ ! -s ${{ env.RSS_FILE }} ]; then
            echo "RSS file is empty or doesn't exist"
            exit 1
          fi
          head -5 ${{ env.RSS_FILE }}
      - name: Get Hashnode articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: ${{ matrix.readme }}
          comment_tag_name: HASHNODE-LATEST-ARTICLES
          max_post_count: 5
          user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36'
          retry_count: 3
          feed_list: './${{ env.RSS_FILE }}'
          commit_message: 'docs: update ${{ matrix.readme }} with latest Hashnode articles'
