name: Hashnode Latest Articles
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Update ${{ matrix.readme }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        readme: [README.md, README.ca.md, README.es.md, README.it.md]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Hashnode articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: ${{ matrix.readme }}
          comment_tag_name: HASHNODE-LATEST-ARTICLES
          max_post_count: 5
          user_agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0'
          accept_header: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8'
          retry_count: 1
          feed_list: ${{ vars.HASHNODE_RSS }}
          commit_message: 'docs: update ${{ matrix.readme }} with latest Hashnode articles'
