name: Hashnode Latest Articles
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Update ${{ matrix.readme }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        readme: [README.md, README.ca.md, README.es.md, README.it.md]
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: ${{ matrix.readme }}
          comment_tag_name: HASHNODE-LATEST-ARTICLES
          max_post_count: 5
          feed_list: ${{ vars.HASHNODE_RSS }}
          commit_message: 'docs: update ${{ matrix.readme }} with latest Hashnode articles'
