name: Hashnode Latest Articles
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    name: 'Update ${{ matrix.readmes }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        readmes: [README.md, README_ca.md, README_es.md, README_it.md]
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ${{ matrix.readmes }}
          comment_tag_name: 'HASHNODE-LATEST-ARTICLES'
          max_post_count: 5
          feed_list: "https://ferranbuireu.hashnode.dev/rss.xml"
          commit_message: 'docs: update ${{ matrix.readmes }} with latest blog posts from Hashnode'
