name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fbuireu
          filename: assets/svg/github-metrics.*
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          config_twemoji: yes
          config_display: columns
          config_animations: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_activity: yes
          plugin_discussions: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_filter: stars:>500 forks:>100
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://ferranbuireu.dev/
          plugin_stars: yes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_people: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: ${{ secrets.STACKOVERFLOW_ID }} 
          repositories_forks: yes
          plugin_contributors: yes
          plugin_licenses_ratio: yes
          plugin_licenses_setup: npm ci
          plugin_reactions: yes
          plugin_reactions_days: 14
          plugin_reactions_details: count, percentage
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_licenses: yes
          plugin_contributors_contributions: yes
          plugin_stargazers: yes
          plugin_topics: yes
          plugin_topics_mode: starred, mastered
          plugin_traffic: yes
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 10
          plugin_music_user: ${{ secrets.SPOTIFY_USER }}
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          
