name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fbuireu
          filename: assets/svg/github-metrics.*
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_achievements: true
          plugin_achievements_secrets: true
          plugin_activity: true
          plugin_discussions: true
          plugin_followup: true
          plugin_followup_sections: repositories, user
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          plugin_lines: true
          plugin_notable: true
          plugin_notable_repositories: true
          plugin_pagespeed: true
          plugin_pagespeed_url: https://ferranbuireu.dev/
          plugin_stars: true
          plugin_languages: true
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: true
          plugin_people: true
          plugin_repositories: true
          plugin_repositories_forks: true
          plugin_stackoverflow: true
          plugin_stackoverflow_user: ${{ secrets.STACKOVERFLOW_ID }} 
          repositories_forks: true
          config_twemoji: true
          plugin_contributors: true
          plugin_licenses_ratio: true
          plugin_licenses_setup: npm ci
          plugin_reactions: true
          plugin_reactions_days: 14
          plugin_reactions_details: count, percentage
          plugin_habits: true
          plugin_habits_facts: true
          plugin_habits_charts: true
          plugin_habits_trim: true
          plugin_licenses: true
          plugin_contributors_contributions: true
          plugin_stargazers: true
          plugin_topics: true
          plugin_topics_mode: starred, mastered
          plugin_traffic: true
          plugin_music: true
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 10
          plugin_music_user: ${{ secrets.SPOTIFY_USER }}
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          
