name: Snake Grid Animation
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  build:
    name: 'style: update GitHub Contribution Snake Grid'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-grid-animation
        with:
          github_user_name: fbuireu
          svg_out_path: dist/github-contribution-snake-grid-animation.svg
      - run: git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SNAKE_GRID_ANIMATION_TOKEN }}
          branch: master
          force: true
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: snake-grid-animation
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_GRID_ANIMATION_TOKEN }}
        
