name: Wakatime Stats
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Update ${{ matrix.readme }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        readme: [README.md, README.ca.md, README.es.md, README.it.md]
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false
      - name: Fetch Wakatime stats
        uses: athul/waka-readme@370590ad8da8f54282ed92aa42b7c25ecbd5a9a6 # master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          TARGET_PATH: ${{ matrix.readme }}
          GH_TOKEN: ${{ secrets.PAT }}
          COMMIT_MESSAGE: 'docs: update ${{ matrix.readme }} with latest WakaTime stats'
      - name: Create and auto-merge PR
        uses: ./.github/actions/create-auto-merge-pr
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'docs: update ${{ matrix.readme }} with latest WakaTime stats'
          title: '🤖 [AUTOMATED] Update WakaTime Stats - ${{ matrix.readme }}'
          branch: 'wakatime-${{ matrix.readme }}-${{ github.run_number }}'
          force-merge: 'true'
